name: Snyk Catch
run-name: Run Snyk Checks
on:
  status:
  check_run:

jobs:
  run-status-checks:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup nodejs
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Run Checks
          run: |
            pip install github-action-utils
            python py-setup/snyk-catch.py